[package]
name = "hnx-devmgr"
version.workspace = true
edition.workspace = true

[[bin]]
name = "devmgr"
path = "src/main.rs"

[dependencies]
libcapsule = { path = "../../../libraries/libcapsule", package = "libcapsule", features = ["runtime"] }
shared = { path = "../../../kernel/shared" }


[features]
capsule = []
