[package]
name = "hnx-devmgr"
version.workspace = true
edition.workspace = true

[[bin]]
name = "devmgr"
path = "src/main.rs"

[dependencies]
capsule_runtime = { path = "../../../libraries/capsule_runtime" }
libcapsule = { path = "../../../libraries/libcapsule", package = "libcapsule" }
shared = { path = "../../../kernel/shared" }


[features]
capsule = []
