[package]
name = "hnx-fileagent"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fileagent"
path = "src/main.rs"

[dependencies]
libcapsule = { path = "../../libraries/libcapsule", package = "libcapsule", features = ["runtime"] }
shared = { path = "../../kernel/shared" }
fatfs = { package = "starry-fatfs", version = "0.4.1-preview.2", default-features = false }

[features]
capsule = []
