[package]
name = "hnx-loader"
version.workspace = true
edition.workspace = true

[[bin]]
name = "loader"
path = "src/main.rs"

[dependencies]
libc.workspace = true
libstd.workspace = true
libcapsule.workspace = true
shared = { path = "../../../kernel/shared" }

# [build]
# rustflags = ["-C", "link-arg=-Tloader.ld"]

[features]
capsule = []
