[workspace]
members = [
    "bootloader",
    "tools/xtask",
    # userspace | capsuleOS
    "userspace/libc",
    "userspace/services/vfs",
    "userspace/services/loader",
    "userspace/services/init",
    "userspace/programs/shell",
]

resolver = "2"

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
opt-level = 0
lto = false
