[workspace.package]
version = "1.0.0-beta4"
edition = "2021"

[workspace.dependencies]
libc = { path = "libraries/libc" }
libstd = { path = "libraries/libstd" }
libcapsule = { path = "libraries/libcapsule" }

[workspace]
members = [
    "bootloader",
    "bootloader/uefi",
    "tools/xtask",
    "tools/ohlink-toolchain/crates/ohlink-format",
    "tools/ohlink-toolchain/crates/ohlink-linker",
    "tools/ohlink-toolchain/crates/ohlink-read",
    # libraries | CapsuleOS runtime contract
    "libraries/libc",
    "libraries/libstd",
    "libraries/libcapsule",
    "libraries/libtty",
    # userspace | capsuleOS
    "userspace/services/devmgr",
    "userspace/services/blkdev",
    "userspace/services/fileagent",
    "userspace/services/loader",
    "userspace/services/procmgr",
    "userspace/services/tty",
    "userspace/services/servicesd",
    "userspace/services/netd",
    "userspace/services/inputd",
    "userspace/services/gpud",
    # "userspace/services/init",
    "userspace/programs/osh",
    "userspace/programs/ls",
    "userspace/programs/cat",
    "userspace/programs/mkdir",
    "userspace/programs/touch",
    "userspace/programs/rm",
    "userspace/programs/rmdir",
    "userspace/programs/ps",
    "userspace/programs/kill",
    "userspace/programs/testall",
    "userspace/programs/dmesg",
    # testloader — 调试期间专用
    # "userspace/programs/testloader",
]

resolver = "2"

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
opt-level = 0
lto = false
debug = 1
