[package]
name = "hnx-graphicd"
version.workspace = true
edition.workspace = true

[[bin]]
name = "graphicd"
path = "src/main.rs"

[dependencies]
libcapsule = { path = "../../../../libraries/libcapsule", package = "libcapsule", features = ["runtime"] }
shared = { path = "../../../shared" }

[features]
capsule = []
