/* 🌌 CapsuleOS — API deprecation notices.
 *
 * This file is hand-maintained (NOT generated by cbindgen).  It
 * documents APIs that are still reachable at the kernel /
 * libcapsule level but are deliberately NOT exposed through the
 * libc public surface, together with the recommended migration.
 *
 * CapsuleOS follows the Fuchsia / Zircon design philosophy:
 * new processes are created through fresh-container spawn, not
 * the legacy fork+exec pattern.  See DEVELOPMENT.md §5 for the
 * full rationale.
 */

/*
 * `fork()` is NOT supported at the libc public boundary on
 * CapsuleOS.
 *
 * The underlying `SYSCALL_FORK` syscall is still wired up
 * because the bash compatibility layer (`/system/bin/bash`
 * running as a privileged service) and `procmgr`'s internal
 * service-spawn path both need it.  Programs that genuinely
 * need raw `fork` semantics can reach it through
 * `libcapsule::syscalls::fork()`.
 *
 * Recommended migration: use `posix_spawn(3)` instead.  See
 * `libraries/libcapsule/src/posix_spawn/API.md` for details.
 * Example:
 *
 *     #include <capsule.h>
 *
 *     pid_t pid;
 *     posix_spawn_file_actions_t fa;
 *     posix_spawnattr_t attr;
 *     posix_spawn_file_actions_init(&fa);
 *     posix_spawnattr_init(&attr);
 *     posix_spawn_file_actions_adddup2(&fa, 1, 1); // stdout -> stdout
 *     if (posix_spawn(&pid, "ls", &fa, &attr,
 *                     (char *const[]){"ls", NULL},
 *                     environ) != 0) {
 *         // spawn failed
 *     }
 *
 * The Fuchsia / Zircon counterpart doesn't expose fork() at all;
 * CapsuleOS keeps the raw syscall alive so bash can run but
 * hides it behind `libcapsule::syscalls::fork()` instead of
 * putting it on the libc ABI.
 */