/* 🌌 Generated by cbindgen of CapsuleOS. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FdEntry FdEntry;

typedef struct FdManager FdManager;

typedef struct FdType FdType;

/**
 * Unified Public Interface for locating and connecting to system services.
 */
typedef struct ServiceManager ServiceManager;

extern Option<FdEntry> USER_FD_TABLE[64];

void _hnx_user_entry(void);

uint8_t *memcpy(uint8_t *dest, const uint8_t *src, uintptr_t n);

uint8_t *memmove(uint8_t *dest, const uint8_t *src, uintptr_t n);

int32_t memcmp(const uint8_t *s1, const uint8_t *s2, uintptr_t n);

uint8_t *memset(uint8_t *s, int32_t c, uintptr_t n);
