[package]
name = "hnx-ps"
version.workspace = true
edition.workspace = true

[features]
default = ["host"]
host = []
capsule = []

[[bin]]
name = "ps"
path = "src/main.rs"

[dependencies]
libc = { path = "../../../libraries/libc", package = "libc" }
libstd = { path = "../../../libraries/libstd", package = "libstd" }
libcapsule = { path = "../../../libraries/libcapsule", package = "libcapsule" }
