[build]
target-dir = "build/target"

[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-A", "warnings",
    "-C", "link-arg=--gc-sections"
]

[target.aarch64-unknown-capsule]
linker = "rust-lld"
rustflags = [
    "-A", "warnings",
    "-C", "link-arg=--gc-sections"
]
