cargo-features = ["profile-rustflags"]

[build]
target-dir = "build/target"


[target.aarch64-unknown-none]
linker = "rust-lld"
rustflags = ["-A", "warnings"]

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = ["-A", "warnings"]

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"
rustflags = ["-A", "warnings"]
