[alias]
xtask = "run --package xtask --"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Ttext=0x10000",
    "-C", "link-arg=--image-base=0x10000",
    "-C", "link-arg=--gc-sections"
]

[target.aarch64-unknown-capsule]
rustflags = [
    "-C", "link-arg=-Ttext=0x10000",
    "-C", "link-arg=--image-base=0x10000",
    "-C", "link-arg=--gc-sections"
]
