[package]
name = "hnx-piped"
version.workspace = true
edition.workspace = true

[[bin]]
name = "piped"
path = "src/main.rs"

[dependencies]
libcapsule = { path = "../../../libraries/libcapsule", package = "libcapsule", features = ["runtime"] }
shared = { path = "../../../kernel/shared" }

[features]
capsule = []