[memory]
kernel_base=0x40080000
user_base=0x10000000
user_size=0x10000000
stack_size=65536
heap_size=1048576
page_size=4096

[toolchain]
rust_target=aarch64-unknown-none
linker=ld.lld
rustflags="-A warnings"
